[project]
name = "factory-async-coordinator"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.async-task-factory]
path = "contracts/async-task-factory.clar"
depends_on = []

[contracts.coordinator-registry]
path = "contracts/coordinator-registry.clar"
depends_on = []

[contracts.async-queue]
path = "contracts/async-queue.clar"
depends_on = []

[contracts.task-scheduler]
path = "contracts/task-scheduler.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
